external: {
  "//third_party/googletest": {
    url: "https://github.com/google/googletest"
    branch: "release-1.8.0"
    build: {
      googletest: {
        type: c++/library
        srcs: [
          "googletest/src/gtest.cc",
          "googletest/src/gtest-death-test.cc",
          "googletest/src/gtest-filepath.cc",
          "googletest/src/gtest-port.cc",
          "googletest/src/gtest-printers.cc",
          "googletest/src/gtest-test-part.cc",
          "googletest/src/gtest-typed-test.cc",
        ]

        link_flags: ["-lpthread"]

        hdrs: ["glob:googletest/include/gtest/**/*.h"]
        includes: [
          "googletest",
          "googletest/include",
        ]
      }
    }
  }
}
